# Joint Offset Configuration for LeKiwi Robot
# This file defines the angle offsets for each joint to align the physical robot with RViz
# Offsets are in degrees and will be converted to servo ticks (4096 ticks = 360 degrees)

joint_offsets:
  # Base zero position for all servos (center position)
  zero_position_base: 2048

  # ARM JOINT-SPECIFIC ANGLE OFFSETS IN DEGREES
  # Positive values rotate in the positive direction
  shoulder_rotation:
    angle_offset_deg: 0.0 # (-2 + 33) degrees

  shoulder_pitch:
    angle_offset_deg: 0.0 # (-92 + 9) degrees

  elbow:
    angle_offset_deg: 0.0 # (82 - 21) degrees

  wrist_pitch:
    angle_offset_deg: 0.0 # (72 - 16) degrees

  wrist_roll:
    angle_offset_deg: 90.0 # (-1 - 30) degrees

  gripper:
    angle_offset_deg: 0.0 # No offset for gripper

  # WHEEL JOINT-SPECIFIC ANGLE OFFSETS IN DEGREES
  # Wheels typically don't need offset adjustments
  left_wheel_drive:
    angle_offset_deg: 0.0

  rear_wheel_drive:
    angle_offset_deg: 0.0

  right_wheel_drive:
    angle_offset_deg: 0.0
