controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lekiwi_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    lekiwi_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # Add individual wheel controllers (velocity control)
    lekiwi_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

lekiwi_controller:
  ros__parameters:
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
      - Wrist_Roll

    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    # Add this to prevent movement on startup
    start_position_control: false
    hold_position_on_startup: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint_trajectory_controller:
        joint1:
          trajectory: 0.05
          goal: 0.03

lekiwi_gripper_controller:
  ros__parameters:
    joints:
      - Gripper
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    # Add this to prevent movement on startup
    start_position_control: false
    hold_position_on_startup: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0

# New wheel controller configuration (velocity control)
lekiwi_wheel_controller:
  ros__parameters:
    joints:
      - left_wheel_drive
      - rear_wheel_drive
      - right_wheel_drive
